### ISSUE TITLE
contigs names are changed during coverage calculation

### ISSUE THREAD

**Issue by michoug** [bluenote-1577/fairy#3]
Hi
I did an assembly with megahit and so got a fasta file with names such as `>k141_689269 flag=1 multi=3.0000 len=1348`

Running the `fairy coverage` command gave me table as such
```
contigName      contigLen       totalAvgDepth   336R_mg 336R_mg-var     337R_mg 337R_mg-var     338R_mg 338R_mg-var     339R_mg 339R_mg-var
k141_393869        1601    5.999999999999999       5.333333333333333       11.162628173828125      8.11111111111111        15.065743446350098      10.555555555555555      21.32179832458496       0       0
k141_886204        1610    1.3325892857142856      2.6875  2.1875  1.1428571428571428      0.234375        1.5     0.375   0       0
k141_2461659       2408    1.4860742705570291      4.482758620689655       4.406036853790283       0       0       1.4615384615384615      0.39780518412590027     0       0
```
Please note the absence of the spaces and everything after them in the table for the contig name

Maybe worth it to mention this potential issue in the `README`, I had a problem with a binning software because of that
Cheers
Greg

**Comment by bluenote-1577** [comment]
Hi @michoug,

Thanks for bringing this up. I'll add an option called `-F` or `--full-contig-names` in a bit and tell you when its released. This default behavior is because software like `coverm` also don't use full contig names.

I'm not sure if metabat works with full contig names... that was my reference for implementation.

**Comment by bluenote-1577** [comment]
Hi @michoug,

The newest source install version should have the `--full-contig-name` option. Let me know if it works.

I'll update the conda version later on.

Thanks
