### ISSUE TITLE
API?

### ISSUE THREAD

**Issue by wwood** [bluenote-1577/fairy#4]
Hi @bluenote-1577 great work here, by the looks.

I was considering incorporating fairy into coverm - since they are both rust do you think it makes sense to use an API? Or should I stick to running it on the cmdline?
Thanks, ben

**Comment by bluenote-1577** [comment]
Hi Ben,

Thanks for interest. I don't have any sort of rust API available, and to be frank, the software was not really written with that in mind. I think commandline would be better... but feel free to open issues if anything arises with the command line.

Jim

**Comment by wwood** [comment]
Alrighty - thanks for the quick and clear reply.
