### ISSUE TITLE
Question about the `.bcsp` file format

### ISSUE THREAD

**Issue by SantaMcCloud** [bluenote-1577/fairy#9]
Hello,

im curious about this file format since  i didnt found anything about it.

Could you give some information about or can link to a documentry about this file format?

Thank you!

**Comment by bluenote-1577** [comment]
@SantaMcCloud it's a special file format compatible only with fairy. It's just the binary format of the k-mer hash table (see the paper). Only fairy can use the file.

**Comment by SantaMcCloud** [comment]
Thank you! i will have a loot at the paper again then
